# CIS Ubuntu 22.04 LTS Level 2 Configuration
# CMMC 2.0: CM.L2-3.4.1, SI.L2-3.14.1
# NIST SP 800-171: 3.4.1, 3.4.2, 3.14.1

metadata:
  name: "CIS Ubuntu 22.04 LTS Benchmark"
  version: "1.0.0"
  level: 2
  compliance_frameworks:
    - "CMMC 2.0"
    - "NIST SP 800-171"
    - "PCI DSS 4.0"
    - "HIPAA"
  description: "CIS Level 2 configuration for Ubuntu 22.04 LTS with CMMC/NIST compliance"
  last_updated: "2025-01-01"

# Filesystem Configuration
filesystem:
  disabled_filesystems:
    - cramfs
    - freevxfs
    - jffs2
    - hfs
    - hfsplus
    - squashfs
    - udf
    - vfat
    - usb-storage  # Level 2 only

  mount_options:
    /tmp:
      options:
        - defaults
        - rw
        - nosuid
        - nodev
        - noexec
        - relatime
      size: 2G
      type: tmpfs

    /var/tmp:
      bind_to: /tmp
      options:
        - nosuid
        - nodev
        - noexec

    /dev/shm:
      options:
        - nosuid
        - nodev
        - noexec

    /home:
      options:
        - nodev
        - nosuid  # Level 2

  permissions:
    /boot/grub/grub.cfg:
      owner: root
      group: root
      mode: "0600"  # Level 2: More restrictive

    /etc/passwd:
      owner: root
      group: root
      mode: "0644"

    /etc/shadow:
      owner: root
      group: shadow
      mode: "0000"  # Level 2: No access

    /etc/gshadow:
      owner: root
      group: shadow
      mode: "0000"  # Level 2: No access

    /etc/group:
      owner: root
      group: root
      mode: "0644"

# Kernel Parameters
kernel:
  sysctl:
    # Network Parameters
    net.ipv4.ip_forward: 0
    net.ipv6.conf.all.forwarding: 0
    net.ipv4.conf.all.send_redirects: 0
    net.ipv4.conf.default.send_redirects: 0
    net.ipv4.conf.all.accept_source_route: 0
    net.ipv4.conf.default.accept_source_route: 0
    net.ipv6.conf.all.accept_source_route: 0
    net.ipv6.conf.default.accept_source_route: 0
    net.ipv4.conf.all.accept_redirects: 0
    net.ipv4.conf.default.accept_redirects: 0
    net.ipv6.conf.all.accept_redirects: 0
    net.ipv6.conf.default.accept_redirects: 0
    net.ipv4.conf.all.secure_redirects: 0
    net.ipv4.conf.default.secure_redirects: 0
    net.ipv4.conf.all.log_martians: 1
    net.ipv4.conf.default.log_martians: 1
    net.ipv4.icmp_echo_ignore_broadcasts: 1
    net.ipv4.icmp_ignore_bogus_error_responses: 1
    net.ipv4.conf.all.rp_filter: 1
    net.ipv4.conf.default.rp_filter: 1
    net.ipv4.tcp_syncookies: 1
    net.ipv6.conf.all.accept_ra: 0
    net.ipv6.conf.default.accept_ra: 0

    # Level 2: Disable IPv6
    net.ipv6.conf.all.disable_ipv6: 1
    net.ipv6.conf.default.disable_ipv6: 1
    net.ipv6.conf.lo.disable_ipv6: 1

    # Security Parameters
    kernel.randomize_va_space: 2
    kernel.panic_on_oops: 1  # Level 2
    kernel.sysrq: 0  # Level 2
    kernel.core_uses_pid: 1
    kernel.kptr_restrict: 2  # Level 2
    kernel.yama.ptrace_scope: 1
    kernel.dmesg_restrict: 1  # Level 2

    # Process Parameters
    fs.suid_dumpable: 0
    fs.protected_hardlinks: 1
    fs.protected_symlinks: 1
    fs.protected_regular: 2  # Level 2
    fs.protected_fifos: 2  # Level 2

  modules:
    blacklisted:
      - dccp
      - sctp
      - rds
      - tipc
      - bluetooth  # Level 2
      - bnep  # Level 2
      - btusb  # Level 2
      - can  # Level 2
      - firewire-core  # Level 2

# Services Configuration
services:
  enabled:
    - auditd
    - rsyslog
    - cron
    - systemd-timesyncd
    - ufw
    - apparmor
    - fail2ban  # Level 2

  disabled:
    # Level 1 services
    - avahi-daemon
    - cups
    - isc-dhcp-server
    - slapd
    - nfs-server
    - rpcbind
    - bind9
    - vsftpd
    - apache2
    - dovecot
    - smbd
    - squid
    - snmpd
    - rsync
    - nis
    # Level 2 additional services
    - xinetd
    - openbsd-inetd
    - telnet
    - rsh-client
    - talk
    - ldap-utils
    - rpcbind
    - bluetooth
    - wireless-tools
    - wpasupplicant

  removed:
    # Level 2: Remove packages entirely
    - xserver-xorg
    - x11-common
    - avahi-daemon
    - cups
    - isc-dhcp-server
    - slapd
    - nfs-kernel-server
    - rpcbind
    - bind9
    - vsftpd
    - apache2
    - dovecot-core
    - samba
    - squid
    - snmpd
    - rsync
    - nis
    - talk
    - telnet

# Firewall Configuration
firewall:
  type: ufw
  default_policies:
    incoming: deny
    outgoing: allow  # Level 2: Can be 'deny' with explicit allows
    routed: deny

  rules:
    # Level 2: Minimal allowed connections
    - direction: in
      port: 22
      protocol: tcp
      from: 10.0.0.0/8  # Restrict to internal network
      comment: "SSH from internal network only"

    # Level 2: Log dropped packets
    - direction: in
      action: log
      log_level: low
      comment: "Log dropped incoming"

  logging:
    enabled: true
    level: medium  # Level 2: Higher logging

# SSH Configuration
ssh:
  config_file: /etc/ssh/sshd_config.d/99-cis.conf

  settings:
    # Basic Settings
    Protocol: 2
    Port: 22  # Consider changing for Level 2
    AddressFamily: inet  # Level 2: IPv4 only
    ListenAddress: 0.0.0.0  # Level 2: Specify interface

    # Logging
    LogLevel: VERBOSE  # Level 2
    SyslogFacility: AUTH

    # Authentication
    LoginGraceTime: 60  # Level 2: Reduced
    PermitRootLogin: "no"
    StrictModes: "yes"
    MaxAuthTries: 3  # Level 2: Reduced
    MaxSessions: 2  # Level 2: Reduced
    MaxStartups: "10:30:60"

    # Password Authentication
    PasswordAuthentication: "no"  # Level 2: Key-based only
    PermitEmptyPasswords: "no"
    ChallengeResponseAuthentication: "no"

    # Public Key Authentication
    PubkeyAuthentication: "yes"
    AuthorizedKeysFile: ".ssh/authorized_keys"
    AuthorizedKeysCommand: none
    AuthorizedKeysCommandUser: nobody

    # Host-based Authentication
    HostbasedAuthentication: "no"
    IgnoreRhosts: "yes"
    IgnoreUserKnownHosts: "yes"  # Level 2

    # Environment
    PermitUserEnvironment: "no"

    # Forwarding
    AllowAgentForwarding: "no"  # Level 2
    AllowTcpForwarding: "no"  # Level 2
    X11Forwarding: "no"
    GatewayPorts: "no"
    PermitTunnel: "no"

    # Timeouts
    ClientAliveInterval: 300  # Level 2: 5 minutes
    ClientAliveCountMax: 0  # Level 2: Immediate disconnect

    # Crypto
    Ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
    MACs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256"
    KexAlgorithms: "curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256"
    HostKeyAlgorithms: "ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256"

    # Other
    UsePAM: "yes"
    UseDNS: "no"  # Level 2
    Banner: /etc/issue.net
    PrintLastLog: "yes"
    Compression: "no"  # Level 2

  allowed_users:
    - admin
    - ubuntu
    # Level 2: Whitelist specific users

  allowed_groups:
    - ssh-users
    # Level 2: Use group-based access

  denied_users:
    - root
    - nobody
    - daemon

# PAM Configuration
pam:
  password_quality:
    minlen: 14  # Level 2: Longer passwords
    dcredit: -1
    ucredit: -1
    ocredit: -1
    lcredit: -1
    minclass: 4  # Level 2: All character classes
    maxrepeat: 2  # Level 2: More restrictive
    maxsequence: 2  # Level 2: More restrictive
    gecoscheck: 1
    dictcheck: 1
    usercheck: 1
    enforce_for_root: true
    retry: 3

  password_hashing:
    algorithm: sha512
    rounds: 5000  # Level 2: More rounds
    remember: 24  # Level 2: Remember more passwords

  account_lockout:
    deny: 3  # Level 2: Less attempts
    unlock_time: 1800  # Level 2: 30 minutes
    root_unlock_time: 1800  # Level 2: Same for root

  session_timeout:
    TMOUT: 600  # Level 2: 10 minutes

# User Account Policies
accounts:
  password_policy:
    PASS_MAX_DAYS: 90  # Level 2: 90 days
    PASS_MIN_DAYS: 7
    PASS_WARN_AGE: 14  # Level 2: 2 weeks warning
    INACTIVE: 30  # Level 2: Lock after 30 days inactive

  umask:
    default: "027"  # Level 2: More restrictive
    root: "077"  # Level 2: Root gets no group/other

  shell_timeout:
    TMOUT: 600  # Level 2: 10 minutes
    readonly_TMOUT: true

  allowed_shells:
    - /bin/bash
    - /bin/sh
    # Level 2: Minimal shells

# Audit Configuration
audit:
  enabled: true

  buffer_size: 8192  # Level 2: Larger buffer
  failure_mode: 2  # Level 2: Panic on failure

  max_log_file: 10  # Level 2: Larger logs
  num_logs: 10  # Level 2: More logs
  max_log_file_action: keep_logs
  space_left: 75
  space_left_action: email  # Level 2: Alert admin
  admin_space_left: 50
  admin_space_left_action: single  # Level 2: Single user mode
  disk_full_action: halt  # Level 2: Halt system
  disk_error_action: halt  # Level 2: Halt system

  rules:
    # Level 2: Comprehensive audit rules
    - "-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change"
    - "-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change"
    - "-a always,exit -F arch=b64 -S clock_settime -k time-change"
    - "-a always,exit -F arch=b32 -S clock_settime -k time-change"
    - "-w /etc/localtime -p wa -k time-change"
    - "-w /etc/group -p wa -k identity"
    - "-w /etc/passwd -p wa -k identity"
    - "-w /etc/gshadow -p wa -k identity"
    - "-w /etc/shadow -p wa -k identity"
    - "-w /etc/security/opasswd -p wa -k identity"
    - "-a always,exit -F arch=b64 -S sethostname -S setdomainname -k system-locale"
    - "-a always,exit -F arch=b32 -S sethostname -S setdomainname -k system-locale"
    - "-w /etc/issue -p wa -k system-locale"
    - "-w /etc/issue.net -p wa -k system-locale"
    - "-w /etc/hosts -p wa -k system-locale"
    - "-w /etc/network -p wa -k system-locale"
    - "-w /etc/apparmor/ -p wa -k MAC-policy"
    - "-w /etc/apparmor.d/ -p wa -k MAC-policy"
    - "-w /var/log/faillog -p wa -k logins"
    - "-w /var/log/lastlog -p wa -k logins"
    - "-w /var/log/tallylog -p wa -k logins"
    - "-w /var/run/utmp -p wa -k session"
    - "-w /var/log/wtmp -p wa -k logins"
    - "-w /var/log/btmp -p wa -k logins"
    - "-a always,exit -F arch=b64 -S chmod -S fchmod -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b64 -S chown -S fchown -S fchownat -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b64 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access"
    - "-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access"
    - "-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access"
    - "-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access"
    # Level 2: Additional monitoring
    - "-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts"
    - "-a always,exit -F arch=b32 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts"
    - "-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete"
    - "-a always,exit -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete"
    - "-w /etc/sudoers -p wa -k scope"
    - "-w /etc/sudoers.d/ -p wa -k scope"
    - "-w /var/log/sudo.log -p wa -k actions"
    - "-w /sbin/insmod -p x -k modules"
    - "-w /sbin/rmmod -p x -k modules"
    - "-w /sbin/modprobe -p x -k modules"
    - "-a always,exit -F arch=b64 -S init_module -S delete_module -k modules"
    - "-a always,exit -F arch=b32 -S init_module -S delete_module -k modules"
    # Level 2: Network monitoring
    - "-a always,exit -F arch=b64 -S connect -S accept -S bind -k network"
    - "-a always,exit -F arch=b32 -S connect -S accept -S bind -k network"
    # Make configuration immutable
    - "-e 2"

# Logging Configuration
logging:
  rsyslog:
    enabled: true
    remote_host: "syslog.example.com"  # Level 2: Central logging
    remote_port: 514
    protocol: tcp  # Level 2: Reliable transport

    rules:
      - "*.emerg                       :omusrmsg:*"
      - "auth,authpriv.*               /var/log/auth.log"
      - "mail.*                        -/var/log/mail.log"
      - "mail.err                      /var/log/mail.err"
      - "*.crit                        /var/log/critical.log"  # Level 2
      - "kern.*                        /var/log/kern.log"  # Level 2
      - "*.*;mail.none;authpriv.none  -/var/log/syslog"

  logrotate:
    frequency: daily  # Level 2: Daily rotation
    rotate: 90  # Level 2: Keep 90 days
    compress: true
    delaycompress: true
    notifempty: true
    create: true
    sharedscripts: true

  permissions:
    /var/log:
      owner: root
      group: syslog
      mode: "0750"  # Level 2: More restrictive

    /var/log/auth.log:
      owner: syslog
      group: adm
      mode: "0600"  # Level 2: More restrictive

    /var/log/syslog:
      owner: syslog
      group: adm
      mode: "0640"  # Level 2: More restrictive

# AIDE Configuration
aide:
  enabled: true

  database: /var/lib/aide/aide.db
  database_new: /var/lib/aide/aide.db.new

  report_url: "file:/var/log/aide/aide.log"

  # Level 2: Comprehensive monitoring
  rules:
    BinLib: "p+i+n+u+g+s+b+m+c+md5+sha256"
    Logs: "p+u+g+i+n+S"
    Devices: "p+i+n+u+g+s+b+c+md5+sha256"
    Databases: "p+n+u+g"
    StaticDir: "p+i+n+u+g"
    ManPages: "p+i+n+u+g+s+b+m+c+md5+sha256"

  directories:
    # Level 2: Monitor everything critical
    /boot: BinLib
    /bin: BinLib
    /sbin: BinLib
    /lib: BinLib
    /lib64: BinLib
    /usr/bin: BinLib
    /usr/sbin: BinLib
    /usr/lib: BinLib
    /usr/lib64: BinLib
    /etc: BinLib
    /root: BinLib
    /var/log: Logs
    /var/lib: Databases
    /dev: Devices

  exclude:
    - /var/log/journal
    - /var/log/sa
    - /var/log/aide/aide.log
    - /var/lib/aide/aide.db
    - /var/lib/aide/aide.db.new

  schedule:
    check: daily  # Level 2: Daily checks
    update: weekly
    time: "03:00"

# AppArmor Configuration
apparmor:
  enabled: true
  mode: enforce  # Level 2: Enforce mode

  profiles:
    - /etc/apparmor.d/usr.sbin.tcpdump
    - /etc/apparmor.d/usr.bin.firefox
    - /etc/apparmor.d/usr.sbin.apache2
    - /etc/apparmor.d/usr.bin.evince

# Additional Security Tools
security_tools:
  fail2ban:
    enabled: true

    jails:
      sshd:
        enabled: true
        maxretry: 3  # Level 2: Less attempts
        bantime: 3600  # Level 2: 1 hour ban
        findtime: 600

    default_bantime: 3600  # Level 2
    default_findtime: 600
    default_maxretry: 3  # Level 2

  rkhunter:
    enabled: true  # Level 2: Rootkit detection
    update_frequency: daily
    scan_frequency: daily

  chkrootkit:
    enabled: true  # Level 2: Additional rootkit detection
    scan_frequency: daily

  clamav:
    enabled: true  # Level 2: Antivirus
    update_frequency: daily
    scan_frequency: daily
    scan_paths:
      - /home
      - /var/www
      - /tmp
      - /var/tmp

# Compliance Evidence
evidence:
  collection_enabled: true

  storage:
    location: /var/log/compliance-evidence
    retention_days: 365  # Level 2: 1 year retention

  artifacts:
    - type: system_inventory
      command: "dpkg -l"
      frequency: daily

    - type: network_connections
      command: "ss -tulpn"
      frequency: hourly

    - type: user_accounts
      command: "getent passwd"
      frequency: daily

    - type: running_processes
      command: "ps auxf"
      frequency: hourly

    - type: open_files
      command: "lsof"
      frequency: hourly

    - type: kernel_modules
      command: "lsmod"
      frequency: daily

    - type: firewall_rules
      command: "ufw status verbose"
      frequency: daily

    - type: audit_status
      command: "auditctl -l"
      frequency: daily

  hash_algorithm: sha256

  encryption:
    enabled: true  # Level 2: Encrypt evidence
    algorithm: aes-256-gcm
    key_derivation: pbkdf2

# FIPS 140-2 Configuration (Level 2)
fips:
  enabled: true

  openssl_config: |
    openssl_conf = openssl_init

    [openssl_init]
    providers = provider_sect
    alg_section = algorithm_sect

    [provider_sect]
    fips = fips_sect
    base = base_sect

    [base_sect]
    activate = 1

    [fips_sect]
    activate = 1

    [algorithm_sect]
    default_properties = fips=yes

  kernel_cmdline: "fips=1 boot=UUID=xxx"

  packages:
    - fips-initramfs
    - fips-updates
    - openssh-server-fips
    - openssh-client-fips
    - libssl1.1-fips
    - libssl-dev-fips
    - strongswan-hmac

# Validation Tests
validation:
  tests:
    - name: "CIS Level 2 Compliance"
      type: openscap
      profile: xccdf_org.ssgproject.content_profile_cis_level2_server

    - name: "STIG Compliance"
      type: openscap
      profile: xccdf_mil.disa.stig_profile_MAC-2_Sensitive

    - name: "Vulnerability Scan"
      type: trivy
      severity: "CRITICAL,HIGH,MEDIUM"

    - name: "Secrets Detection"
      type: trufflehog
      paths:
        - /etc
        - /root
        - /home

    - name: "Network Security"
      type: nmap
      ports: "1-65535"

    - name: "File Integrity"
      type: aide
      check: true