# Security Alert Rules
# CMMC 2.0: IR.L2-3.6.1, IR.L2-3.6.2 - Incident Response
# NIST SP 800-171: 3.6.1, 3.6.2 - Incident Response
# NIST SP 800-53: IR-4, IR-5, IR-6 - Incident Handling

groups:
  - name: security_alerts
    interval: 30s
    rules:
      # Critical vulnerability detection
      - alert: CriticalVulnerabilityDetected
        expr: |
          max(security_scan_vulnerability_count{severity="CRITICAL"}) > 0
        for: 1m
        labels:
          severity: critical
          category: security
          compliance: "CMMC:RA.L2-3.11.2,NIST171:3.11.2,NIST53:RA-5"
        annotations:
          summary: "Critical vulnerability detected in {{ $labels.component }}"
          description: "{{ $value }} critical vulnerabilities found in {{ $labels.component }}. Immediate action required."
          runbook_url: "https://docs.example.com/runbooks/critical-vulnerability"
          dashboard_url: "https://grafana.example.com/d/security/security-scanning-metrics"

      # High vulnerability threshold
      - alert: HighVulnerabilityThresholdExceeded
        expr: |
          sum(security_scan_vulnerability_count{severity="HIGH"}) > 10
        for: 5m
        labels:
          severity: warning
          category: security
          compliance: "CMMC:RA.L2-3.11.2,NIST171:3.11.2"
        annotations:
          summary: "High vulnerability count exceeds threshold"
          description: "{{ $value }} high severity vulnerabilities detected across components"
          runbook_url: "https://docs.example.com/runbooks/high-vulnerability"

      # Security scan failure
      - alert: SecurityScanFailure
        expr: |
          up{job="security_scans"} == 0 or
          security_scan_last_success_timestamp < (time() - 3600)
        for: 10m
        labels:
          severity: critical
          category: security
          compliance: "CMMC:CA.L2-3.12.3,NIST171:3.12.3"
        annotations:
          summary: "Security scanning is failing"
          description: "Security scan exporter is down or scans haven't succeeded in over 1 hour"
          runbook_url: "https://docs.example.com/runbooks/scan-failure"

      # Malware detection
      - alert: MalwareDetected
        expr: |
          security_scan_malware_detected > 0
        for: 1m
        labels:
          severity: critical
          category: security
          compliance: "CMMC:SI.L2-3.14.2,NIST171:3.14.2,NIST53:SI-3"
        annotations:
          summary: "Malware detected in {{ $labels.component }}"
          description: "Malware signature found in {{ $labels.file }}. Isolate and investigate immediately."
          runbook_url: "https://docs.example.com/runbooks/malware-response"

      # CVSS score threshold
      - alert: HighCVSSScore
        expr: |
          max(security_scan_cvss_score) by (component) > 9.0
        for: 5m
        labels:
          severity: warning
          category: security
          compliance: "CMMC:RA.L2-3.11.3,NIST171:3.11.3"
        annotations:
          summary: "Component {{ $labels.component }} has critical CVSS score"
          description: "CVSS score of {{ $value }} detected for {{ $labels.component }}"
          runbook_url: "https://docs.example.com/runbooks/cvss-remediation"

      # Secrets exposure
      - alert: SecretsExposed
        expr: |
          security_scan_secrets_found > 0
        for: 1m
        labels:
          severity: critical
          category: security
          compliance: "CMMC:IA.L2-3.5.10,NIST171:3.5.10,NIST53:IA-5"
        annotations:
          summary: "Secrets exposed in {{ $labels.repository }}"
          description: "{{ $value }} secrets found in {{ $labels.repository }}. Rotate credentials immediately."
          runbook_url: "https://docs.example.com/runbooks/secrets-exposure"

      # SonarQube security hotspots
      - alert: SonarQubeSecurityHotspots
        expr: |
          sonarqube_security_hotspots > 5
        for: 15m
        labels:
          severity: warning
          category: security
          compliance: "CMMC:CA.L2-3.12.3,NIST171:3.12.3"
        annotations:
          summary: "Security hotspots in {{ $labels.project }}"
          description: "{{ $value }} security hotspots require review in {{ $labels.project }}"
          dashboard_url: "https://sonarqube.example.com/dashboard?id={{ $labels.project }}"

      # Unauthorized access attempts
      - alert: UnauthorizedAccessAttempts
        expr: |
          rate(gitea_failed_login_attempts_total[5m]) > 5
        for: 5m
        labels:
          severity: warning
          category: security
          compliance: "CMMC:AC.L2-3.1.1,NIST171:3.1.1,NIST53:AC-2"
        annotations:
          summary: "Multiple failed login attempts detected"
          description: "{{ $value }} failed login attempts per second on Gitea"
          runbook_url: "https://docs.example.com/runbooks/brute-force"

      # Certificate expiry
      - alert: CertificateExpiringSoon
        expr: |
          probe_ssl_earliest_cert_expiry - time() < 7 * 24 * 3600
        for: 1h
        labels:
          severity: warning
          category: security
          compliance: "CMMC:SC.L2-3.13.8,NIST171:3.13.8,NIST53:SC-8"
        annotations:
          summary: "SSL certificate expiring soon for {{ $labels.instance }}"
          description: "Certificate expires in {{ $value | humanizeDuration }}"
          runbook_url: "https://docs.example.com/runbooks/cert-renewal"

      # Container security
      - alert: PrivilegedContainerRunning
        expr: |
          container_privileged{name!=""} > 0
        for: 5m
        labels:
          severity: warning
          category: security
          compliance: "CMMC:AC.L2-3.1.5,NIST171:3.1.5,NIST53:AC-6"
        annotations:
          summary: "Privileged container running: {{ $labels.name }}"
          description: "Container {{ $labels.name }} is running with privileged access"
          runbook_url: "https://docs.example.com/runbooks/container-security"

      # Compliance scan failures
      - alert: ComplianceScanFailure
        expr: |
          compliance_scan_failures_total > 0
        for: 15m
        labels:
          severity: critical
          category: compliance
          compliance: "CMMC:CA.L2-3.12.1,NIST171:3.12.1,NIST53:CA-2"
        annotations:
          summary: "Compliance scan failures detected"
          description: "{{ $value }} compliance scan failures in the last 15 minutes"
          runbook_url: "https://docs.example.com/runbooks/compliance-scan"

      # Security control coverage
      - alert: LowSecurityControlCoverage
        expr: |
          compliance_control_coverage_percent < 80
        for: 30m
        labels:
          severity: warning
          category: compliance
          compliance: "CMMC:CA.L2-3.12.1,NIST171:3.12.1"
        annotations:
          summary: "Security control coverage below threshold"
          description: "Control coverage at {{ $value }}%, below 80% threshold"
          dashboard_url: "https://grafana.example.com/d/compliance/compliance-metrics"